### PR TITLE
Add a Jenkinsfile

### PR DESCRIPTION
**Pull request by abayer**
cc @reviewbybees

### CODE REVIEW

**Comment by rsandell** [comment]
Yes, should do the plugin pom 2.x bump first I guess.
@abayer you said you would do that?

**Comment by rsandell** [comment]
I merged something where `pluginRepositories` was added, so I merged this to see what would happen :)

**Comment by rsandell** [comment]
Seems like the tests fails spectacularly on Windows :)

**Comment by jglick** [comment]
The idea is to get the CI build passing _before_ merging the PR adding `Jenkinsfile`…

**Comment by rsandell** [comment]
Well I couldn't figure out how to test it without merging first, now we at least have some for of CI, the windows errors seems to be environmental, not because of bugs in the plugin.

**Comment by rsandell** [comment]
Well at least they where environmental issues the first two runs. Now it shoes some design flaws in the tests :)

**Comment by jglick** [comment]
> I couldn't figure out how to test it without merging first

You do have to have write permission to the repository.

**Comment by rsandell** [comment]
Yes but it was easier to merge, test and fix on master than waiting for Andrew to come back or close and make a new pr :)

**Comment by abayer** [comment]
I suck! =)

**Pull request merged**
