### PR TITLE
Removing runtime dep on workflow-cps

### PR DESCRIPTION
**Pull request by jglick**
Noticed during review of #36. I do not care if this is incompatible. More important to fix this bad dependency.

@reviewbybees

### CODE REVIEW

**Comment by rsandell** [comment]
WHY?

**Comment by daniel-beck** [comment]
Seems like `optional = true` would make a good compromise (even though we all hate it).

**Comment by rsandell** [comment]
Some may hate `optional = true` but I haven't been convinced of why it is a bad thing yet.
If it indeed is just a matter of "it will perhaps not be there in a far of future" then making it an optional dependency should be the way to go I think.

**Comment by jglick** [comment]
I prefer removing the dep to making to optional, but if making it optional is what I need to do in order to get the hard dep removed, so be it.

**Comment by jglick** [comment]
Really, exposing actual `maven-model` classes to the Pipeline script is not a good idea. What you ought to be doing instead is returning some shim classes or POJOs with a similar structure.

(Better yet, people should not use `readMavenPom` or `writeMavenPom`. These should never have been written. If you want to manipulate `pom.xml`s programmatically, there are command-line tools to do that.)

**Pull request merged**
