### PR TITLE
Porting https://github.com/jglick/tee-step-plugin to pipeline-utility-steps

### PR DESCRIPTION
**Pull request by jglick**
Targeted to https://github.com/jenkinsci/pipeline-utility-steps-plugin/pull/36.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Windows build failure, fixing…

**Comment by jglick** [comment]
@reviewbybees done

**Comment by rsandell** [comment]
Holding off merging this until #36 is ready for merge, so we don't mix things up too much in that pr.

**Comment by bpedersen2** [comment]
Seems like the snippet generation is not correct: Even if entering a filename, the output is just:
tee {
}

**Comment by rsandell** [comment]
Indeed, I guess `<f:entry name="file" title="File">` should actually be `<f:entry field="file" title="File">`

**Pull request merged**
