### PR TITLE
Bump core version to 2.361.4 and plugin parent to 4.53

### PR DESCRIPTION
**Pull request by rsandell**
To fix Java 11 build errors

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by rsandell** [comment]
@basil any ideas why this works locally for me but not on CI?

**Comment by basil** [comment]
Because you're running the CI build on Java 8.

https://www.jenkins.io/blog/2022/12/14/require-java-11/#adjust-the-jenkinsfile-to-use-java-11-or-newer

**Comment by rsandell** [comment]
Ah, thank you! I assumed buildPlugin was slightly smarter and could figure that out :sweat_smile:

**Comment by basil** [comment]
Tried to make that so but others objected in https://github.com/jenkins-infra/pipeline-library/pull/541#issuecomment-1342884874

**Pull request merged**
