### PR TITLE
sha256 step added

### PR DESCRIPTION
**Pull request by offa**
Adds a `sha256` step; with the implementation of `sha256` and `sha1` is extracted to a base class.

### To Do

- [ ] ❓ Reduce the visibility of the base class?
- [x] Fix `configRoundTrip `of `FileSha256StepTest `

------------------

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] ~~Link to relevant pull requests, esp. upstream and downstream changes~~
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by offa** [comment]
The failing `configRoundTrip` Test of SHA256 is wired. The implementation and it's test case is the same for SHA1 and SHA256, the latter fails though.

**Review by rsandell — APPROVED** [review]

**Comment by rsandell** [comment]
Needs a rebase of your other fix :)

**Comment by rsandell** [comment]
I'm handling the merge conflict now, so I can release before EOB :)

**Comment by offa** [comment]
Thank you!

**Pull request merged**
